// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package register

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (RegisterFilesConfig) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (RegisterFilesConfig) mustJsonMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	return string(raw)
}

func (RegisterFilesConfig) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in RegisterFilesConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg RegisterFilesConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("RegisterFilesConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&filesConfig.version, fmt.Sprintf("%v%v", prefix, "version"), filesConfig.version, "version of the entity to be registered with flyte.")
	cmdFlags.BoolVar(&filesConfig.skipOnError, fmt.Sprintf("%v%v", prefix, "skipOnError"), filesConfig.skipOnError, "fail fast when registering files.")
	cmdFlags.StringToStringVar(&filesConfig.stringMap, fmt.Sprintf("%v%v", prefix, "stringMap"), filesConfig.stringMap, "Passes a string map.")
	cmdFlags.StringToIntVar(&filesConfig.intMap, fmt.Sprintf("%v%v", prefix, "intMap"), filesConfig.intMap, "Passes an int map.")
	return cmdFlags
}
