// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

<<<<<<< HEAD:cmd/config/config_flags.go
package config
=======
package clusterresourceattribute
>>>>>>> Added cluster resource attribute support:cmd/config/subcommand/clusterresourceattribute/attrupdateconfig_flags.go

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
<<<<<<< HEAD:cmd/config/config_flags.go
func (Config) elemValueOrNil(v interface{}) interface{} {
=======
func (AttrUpdateConfig) elemValueOrNil(v interface{}) interface{} {
>>>>>>> Added cluster resource attribute support:cmd/config/subcommand/clusterresourceattribute/attrupdateconfig_flags.go
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

<<<<<<< HEAD:cmd/config/config_flags.go
func (Config) mustMarshalJSON(v json.Marshaler) string {
=======
func (AttrUpdateConfig) mustMarshalJSON(v json.Marshaler) string {
>>>>>>> Added cluster resource attribute support:cmd/config/subcommand/clusterresourceattribute/attrupdateconfig_flags.go
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

<<<<<<< HEAD:cmd/config/config_flags.go
// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "project"), defaultConfig.Project, "Specifies the project to work on.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "domain"), defaultConfig.Domain, "Specified the domain to work on.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "output"), defaultConfig.Domain, "Specified the output type.")
=======
// GetPFlagSet will return strongly types pflags for all fields in AttrUpdateConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg AttrUpdateConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("AttrUpdateConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&(DefaultUpdateConfig.AttrFile), fmt.Sprintf("%v%v", prefix, "attrFile"), DefaultUpdateConfig.AttrFile, "attribute file name to be used for updating attribute for the resource type.")
>>>>>>> Added cluster resource attribute support:cmd/config/subcommand/clusterresourceattribute/attrupdateconfig_flags.go
	return cmdFlags
}
