admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///192.168.64.87:30081
  # endpoint: dns:///flyte.lyft.net
  insecure: true
logger:
  show-source: true
  level: 1
