package compile

//go:generate pflags CompileConfig --default-var DefaultCompileConfig --bind-default-var
var (
	DefaultCompileConfig = &CompileConfig{}
)

// CompileConfig stores the flags required by compile command
type CompileConfig struct {
	File string `json:"file" pflag:",Path to a flyte package file. Flyte packages are tgz files generated by pyflyte or jflyte."`
}
