// Code generated by "enumer -type=ImagePullPolicy -trimprefix=ImagePullPolicy"; DO NOT EDIT.

package sandbox

import (
	"fmt"
	"strings"
)

const _ImagePullPolicyName = "AlwaysIfNotPresentNever"

var _ImagePullPolicyIndex = [...]uint8{0, 6, 18, 23}

const _ImagePullPolicyLowerName = "alwaysifnotpresentnever"

func (i ImagePullPolicy) String() string {
	if i < 0 || i >= ImagePullPolicy(len(_ImagePullPolicyIndex)-1) {
		return fmt.Sprintf("ImagePullPolicy(%d)", i)
	}
	return _ImagePullPolicyName[_ImagePullPolicyIndex[i]:_ImagePullPolicyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ImagePullPolicyNoOp() {
	var x [1]struct{}
	_ = x[ImagePullPolicyAlways-(0)]
	_ = x[ImagePullPolicyIfNotPresent-(1)]
	_ = x[ImagePullPolicyNever-(2)]
}

var _ImagePullPolicyValues = []ImagePullPolicy{ImagePullPolicyAlways, ImagePullPolicyIfNotPresent, ImagePullPolicyNever}

var _ImagePullPolicyNameToValueMap = map[string]ImagePullPolicy{
	_ImagePullPolicyName[0:6]:        ImagePullPolicyAlways,
	_ImagePullPolicyLowerName[0:6]:   ImagePullPolicyAlways,
	_ImagePullPolicyName[6:18]:       ImagePullPolicyIfNotPresent,
	_ImagePullPolicyLowerName[6:18]:  ImagePullPolicyIfNotPresent,
	_ImagePullPolicyName[18:23]:      ImagePullPolicyNever,
	_ImagePullPolicyLowerName[18:23]: ImagePullPolicyNever,
}

var _ImagePullPolicyNames = []string{
	_ImagePullPolicyName[0:6],
	_ImagePullPolicyName[6:18],
	_ImagePullPolicyName[18:23],
}

// ImagePullPolicyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ImagePullPolicyString(s string) (ImagePullPolicy, error) {
	if val, ok := _ImagePullPolicyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ImagePullPolicyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ImagePullPolicy values", s)
}

// ImagePullPolicyValues returns all values of the enum
func ImagePullPolicyValues() []ImagePullPolicy {
	return _ImagePullPolicyValues
}

// ImagePullPolicyStrings returns a slice of all String values of the enum
func ImagePullPolicyStrings() []string {
	strs := make([]string, len(_ImagePullPolicyNames))
	copy(strs, _ImagePullPolicyNames)
	return strs
}

// IsAImagePullPolicy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ImagePullPolicy) IsAImagePullPolicy() bool {
	for _, v := range _ImagePullPolicyValues {
		if i == v {
			return true
		}
	}
	return false
}
