// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package get

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsTaskConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementTaskConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsTaskConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookTaskConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementTaskConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_TaskConfig(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookTaskConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_TaskConfig(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_TaskConfig(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_TaskConfig(val, result))
}

func testDecodeRaw_TaskConfig(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_TaskConfig(vStringSlice, result))
}

func TestTaskConfig_GetPFlagSet(t *testing.T) {
	val := TaskConfig{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestTaskConfig_SetFlags(t *testing.T) {
	actual := TaskConfig{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_execFile", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("execFile", testValue)
			if vString, err := cmdFlags.GetString("execFile"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vString), &actual.ExecFile)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_version", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("version", testValue)
			if vString, err := cmdFlags.GetString("version"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vString), &actual.Version)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_latest", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("latest", testValue)
			if vBool, err := cmdFlags.GetBool("latest"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vBool), &actual.Latest)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_filter.field-selector", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("filter.field-selector", testValue)
			if vString, err := cmdFlags.GetString("filter.field-selector"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vString), &actual.Filter.FieldSelector)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_filter.sort-by", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("filter.sort-by", testValue)
			if vString, err := cmdFlags.GetString("filter.sort-by"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vString), &actual.Filter.SortBy)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_filter.limit", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("filter.limit", testValue)
			if vInt32, err := cmdFlags.GetInt32("filter.limit"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vInt32), &actual.Filter.Limit)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_filter.asc", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("filter.asc", testValue)
			if vBool, err := cmdFlags.GetBool("filter.asc"); err == nil {
				testDecodeJson_TaskConfig(t, fmt.Sprintf("%v", vBool), &actual.Filter.Asc)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
