// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package taskresourceattribute

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in AttrFetchConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg AttrFetchConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("AttrFetchConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&(DefaultFetchConfig.AttrFile), fmt.Sprintf("%v%v", prefix, "attrFile"), DefaultFetchConfig.AttrFile, "attribute file name to be used for generating attribute for the resource type.")
	return cmdFlags
}
