// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package taskresourceattribute

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in AttrDeleteConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg AttrDeleteConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("AttrDeleteConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&(DefaultDelConfig.AttrFile), fmt.Sprintf("%v%v", prefix, "attrFile"), DefaultDelConfig.AttrFile, "attribute file name to be used for delete attribute for the resource type.")
	return cmdFlags
}
