// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package serialize

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_Config(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_Config(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_Config(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_Config(val, result))
}

func testDecodeRaw_Config(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_Config(vStringSlice, result))
}

func TestConfig_GetPFlagSet(t *testing.T) {
	val := Config{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestConfig_SetFlags(t *testing.T) {
	actual := Config{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_image", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("image", testValue)
			if vString, err := cmdFlags.GetString("image"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.Image)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_registry", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("registry", testValue)
			if vString, err := cmdFlags.GetString("registry"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.Registry)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_service-account", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("service-account", testValue)
			if vString, err := cmdFlags.GetString("service-account"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ServiceAccount)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_version", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("version", testValue)
			if vString, err := cmdFlags.GetString("version"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.Version)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_output-dir", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("output-dir", testValue)
			if vString, err := cmdFlags.GetString("output-dir"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.OutputDir)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_output-dir-prefix", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("output-dir-prefix", testValue)
			if vString, err := cmdFlags.GetString("output-dir-prefix"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.OutputDirprefix)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_flyte-aws-endpoint", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("flyte-aws-endpoint", testValue)
			if vString, err := cmdFlags.GetString("flyte-aws-endpoint"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.FlyteAwsEndpoint)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_flyte-aws-key", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("flyte-aws-key", testValue)
			if vString, err := cmdFlags.GetString("flyte-aws-key"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.FlyteAwsKey)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_flyte-aws-secret", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("flyte-aws-secret", testValue)
			if vString, err := cmdFlags.GetString("flyte-aws-secret"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.FlyteAwsSecret)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_command", func(t *testing.T) {

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("command", testValue)
			if vString, err := cmdFlags.GetString("command"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.Command)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
