// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package project

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (CreateConfig) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (CreateConfig) mustJsonMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	return string(raw)
}

func (CreateConfig) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in CreateConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg CreateConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("CreateConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&DefaultCreateConfig.ID, fmt.Sprintf("%v%v", prefix, "id"), DefaultCreateConfig.ID, "id for the project specified as argument.")
	cmdFlags.StringVar(&DefaultCreateConfig.Name, fmt.Sprintf("%v%v", prefix, "name"), DefaultCreateConfig.Name, "name for the project specified as argument.")
	cmdFlags.StringVar(&DefaultCreateConfig.File, fmt.Sprintf("%v%v", prefix, "file"), DefaultCreateConfig.File, "file for the project definition.")
	cmdFlags.StringVar(&DefaultCreateConfig.Description, fmt.Sprintf("%v%v", prefix, "description"), DefaultCreateConfig.Description, "description for the project specified as argument.")
	cmdFlags.StringToStringVar(&DefaultCreateConfig.Labels, fmt.Sprintf("%v%v", prefix, "labels"), DefaultCreateConfig.Labels, "labels for the project specified as argument.")
	cmdFlags.BoolVar(&DefaultCreateConfig.DryRun, fmt.Sprintf("%v%v", prefix, "dryRun"), DefaultCreateConfig.DryRun, "execute command without making any modifications.")
	return cmdFlags
}
