// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package project

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (ProjectCreateConfig) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (ProjectCreateConfig) mustJsonMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	return string(raw)
}

func (ProjectCreateConfig) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in ProjectCreateConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg ProjectCreateConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("ProjectCreateConfig", pflag.ExitOnError)
	cmdFlags.StringVar(&DefaultProjectCreateConfig.ID, fmt.Sprintf("%v%v", prefix, "id"), DefaultProjectCreateConfig.ID, "id for the project specified as argument.")
	cmdFlags.StringVar(&DefaultProjectCreateConfig.Name, fmt.Sprintf("%v%v", prefix, "name"), DefaultProjectCreateConfig.Name, "name for the project specified as argument.")
	cmdFlags.StringVar(&DefaultProjectCreateConfig.File, fmt.Sprintf("%v%v", prefix, "file"), DefaultProjectCreateConfig.File, "file for the project definition.")
	cmdFlags.StringVar(&DefaultProjectCreateConfig.Description, fmt.Sprintf("%v%v", prefix, "description"), DefaultProjectCreateConfig.Description, "description for the project specified as argument.")
	cmdFlags.StringToStringVar(&DefaultProjectCreateConfig.Labels, fmt.Sprintf("%v%v", prefix, "labels"), DefaultProjectCreateConfig.Labels, "labels for the project specified as argument.")
	cmdFlags.BoolVar(&DefaultProjectCreateConfig.DryRun, fmt.Sprintf("%v%v", prefix, "dryRun"), DefaultProjectCreateConfig.DryRun, "execute command without making any modifications.")
	return cmdFlags
}
