// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package update

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsTaskResourceAttrConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementTaskResourceAttrConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsTaskResourceAttrConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookTaskResourceAttrConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementTaskResourceAttrConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_TaskResourceAttrConfig(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookTaskResourceAttrConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_TaskResourceAttrConfig(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_TaskResourceAttrConfig(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_TaskResourceAttrConfig(val, result))
}

func testDecodeSlice_TaskResourceAttrConfig(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_TaskResourceAttrConfig(vStringSlice, result))
}

func TestTaskResourceAttrConfig_GetPFlagSet(t *testing.T) {
	val := TaskResourceAttrConfig{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestTaskResourceAttrConfig_SetFlags(t *testing.T) {
	actual := TaskResourceAttrConfig{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_attrFile", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("attrFile"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.AttrFile), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("attrFile", testValue)
			if vString, err := cmdFlags.GetString("attrFile"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.AttrFile)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_cpuDefault", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("cpuDefault"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.CpuDefault), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("cpuDefault", testValue)
			if vString, err := cmdFlags.GetString("cpuDefault"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.CpuDefault)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_gpuDefault", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("gpuDefault"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.GpuDefault), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("gpuDefault", testValue)
			if vString, err := cmdFlags.GetString("gpuDefault"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.GpuDefault)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_memoryDefault", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("memoryDefault"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.MemoryDefault), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("memoryDefault", testValue)
			if vString, err := cmdFlags.GetString("memoryDefault"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.MemoryDefault)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_storageDefault", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("storageDefault"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.StorageDefault), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("storageDefault", testValue)
			if vString, err := cmdFlags.GetString("storageDefault"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.StorageDefault)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_cpuLimit", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("cpuLimit"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.CpuLimit), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("cpuLimit", testValue)
			if vString, err := cmdFlags.GetString("cpuLimit"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.CpuLimit)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_gpuLimit", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("gpuLimit"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.GpuLimit), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("gpuLimit", testValue)
			if vString, err := cmdFlags.GetString("gpuLimit"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.GpuLimit)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_memoryLimit", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("memoryLimit"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.MemoryLimit), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("memoryLimit", testValue)
			if vString, err := cmdFlags.GetString("memoryLimit"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.MemoryLimit)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_storageLimit", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("storageLimit"); err == nil {
				assert.Equal(t, string(matchableTaskRsConfig.StorageLimit), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("storageLimit", testValue)
			if vString, err := cmdFlags.GetString("storageLimit"); err == nil {
				testDecodeJson_TaskResourceAttrConfig(t, fmt.Sprintf("%v", vString), &actual.StorageLimit)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
