// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package update

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (TaskResourceAttrConfig) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (TaskResourceAttrConfig) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in TaskResourceAttrConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg TaskResourceAttrConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("TaskResourceAttrConfig", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "attrFile"), matchableTaskRsConfig.AttrFile, "attribute file name to be used for generating attribute for the resource type.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "cpuDefault"), matchableTaskRsConfig.CpuDefault, "cpuDefault to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "gpuDefault"), matchableTaskRsConfig.GpuDefault, "gpuDefault to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "memoryDefault"), matchableTaskRsConfig.MemoryDefault, "memoryDefault to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "storageDefault"), matchableTaskRsConfig.StorageDefault, "storageDefault to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "cpuLimit"), matchableTaskRsConfig.CpuLimit, "cpuLimit to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "gpuLimit"), matchableTaskRsConfig.GpuLimit, "gpuLimit to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "memoryLimit"), matchableTaskRsConfig.MemoryLimit, "memoryLimit to be assigned for workflow or tasks.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "storageLimit"), matchableTaskRsConfig.StorageLimit, "storageLimit to be assigned for workflow or tasks.")
	return cmdFlags
}
