name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run GoReleaser dry run
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot  --skip-publish --rm-dist
      - name: Unit Tests
        env:
          GO111MODULE: "on"
          CI_ENV: "true"
        run: make install && make test_unit_without_flag
      - name: Push CodeCov
        uses: codecov/codecov-action@v1.0.5
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        env:
          GO111MODULE: "on"
        run: make install && make lint
