name: build

on:
  pull_request:
    branches:
      - master

jobs:
  dry-run-goreleaser:
    name: Dry Run Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run GoReleaser dry run
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot  --skip-publish --rm-dist

  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Unit Tests
        env:
          GO111MODULE: "on"
          CI_ENV: "true"
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
        run: make install && make test_unit_without_flag
      - name: Push CodeCov
        uses: codecov/codecov-action@v1.0.5
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true


  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Lint
        env:
          GO111MODULE: "on"
        run: make install && make lint

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Go generate and diff
        run: DELTA_CHECK=true make generate