name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: docs-pip-${{ runner.os }}-${{ hashFiles('doc-requirements.txt') }}-${{ hashFiles('doc-requirements.in') }}
          restore-keys: docs-pip-
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.FLYTE_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FLYTE_BOT_GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Install Dependencies
        run: |
          # Install all requirments
          pip install -r doc-requirements.txt
      - name: Generate documentation
        run: |
          make -C docs gendocs
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update documentation
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-documentation
          delete-branch: true
          title: 'Update documentation'
          body: |
            Update documentation
            - Auto-generated by [flyte-bot]
          labels: |
            documentation
          team-reviewers: |
            owners
            maintainers
          draft: false
