name: Test Getting started

on:
  pull_request:
    branches:
      - master

jobs:
  sandbox:
    name: Test Getting started
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - name: Build Flytectl binary
        run: make compile
      - name: Setup env
        run: |
          mkdir -p ~/.flyte/k3s && touch ~/.flyte/k3s/k3s.yaml && chmod 666 ~/.flyte/k3s/k3s.yaml
      - name: Create a sandbox cluster
        run: bin/flytectl sandbox start
      - name: Setup flytectl config
        run: bin/flytectl config init
      - name: Register cookbook
        run: bin/flytectl register examples -d development  -p flytesnacks
      - name: Teardown Sandbox cluster
        run: bin/flytectl sandbox teardown
