name: Test Getting started

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test Getting started
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - name: Build Flytectl binary
        run: make compile
      - name: Create a sandbox cluster
        run: bin/flytectl sandbox start
      - name: Register cookbook
        run: bin/flytectl register examples -d development  -p flytesnacks || true
      - name: Teardown Sandbox cluster
        run: bin/flytectl sandbox teardown
